require_dependency 'ar-ondemand/on_demand'
require_dependency 'ar-ondemand/for_reading'
require_dependency 'ar-ondemand/for_streaming'
require_dependency 'ar-ondemand/for_enumeration_reading'
require_dependency 'ar-ondemand/for_enumeration_streaming'
require_dependency 'ar-ondemand/delete_all_by_pk'
